spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: demo_user
    password: demo_password
    driver-class-name: com.mysql.jdbc.Driver

mybatis.config-location: classpath:mybatis-config.xml
    
logging:
  level:
    cn.xbsafe.myapp.mapper: TRACE    